package IkoiEVoucher;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Rick
 */
public class MainFrame extends javax.swing.JFrame {

    private final MainPackage mp;
    private DefaultComboBoxModel dcbm1, dcbm2;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() throws IOException, Exception {
        mp = new MainPackage();
        this.dcbm1 = new DefaultComboBoxModel(mp.getServiceTitle().toArray());
        this.dcbm2 = new DefaultComboBoxModel(mp.getAddonTitle().toArray());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        printOutButton = new javax.swing.JButton();
        firstNameLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        serviceLabel = new javax.swing.JLabel();
        addonLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        LastNameTextField = new javax.swing.JTextField();
        treatmentComboBox = new javax.swing.JComboBox<>();
        addonComboBox = new javax.swing.JComboBox<>();
        voucherNumberLabel = new javax.swing.JLabel();
        voucherNumberTextFeild = new javax.swing.JTextField();
        AmountLabel = new javax.swing.JLabel();
        amountTextFeild = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        printOutButton.setText("Save & Print");
        printOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printOutButtonActionPerformed(evt);
            }
        });

        firstNameLabel.setText("First name:");

        LastNameLabel.setText("Last name:");

        serviceLabel.setText("Service:");

        addonLabel.setText("Addon:");

        LastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTextFieldActionPerformed(evt);
            }
        });

        treatmentComboBox.setModel(dcbm1);

        addonComboBox.setModel(dcbm2);

        voucherNumberLabel.setText("Voucher number:");

        voucherNumberTextFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voucherNumberTextFeildActionPerformed(evt);
            }
        });

        AmountLabel.setText("Number of treatment:");

        amountTextFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTextFeildActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLabel)
                            .addComponent(LastNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LastNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                            .addComponent(firstNameTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serviceLabel)
                            .addComponent(voucherNumberLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(voucherNumberTextFeild)
                            .addComponent(treatmentComboBox, 0, 355, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addonLabel)
                            .addComponent(AmountLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(addonComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(amountTextFeild)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(printOutButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastNameLabel)
                    .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voucherNumberLabel)
                    .addComponent(voucherNumberTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serviceLabel)
                    .addComponent(treatmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addonLabel)
                    .addComponent(addonComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AmountLabel)
                    .addComponent(amountTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(printOutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTextFieldActionPerformed

    private void printOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printOutButtonActionPerformed
        // TODO add your handling code here:
        try {
            Calendar c = Calendar.getInstance();
            String fileName = new SimpleDateFormat("dd_MM_yyyy").format(c.getTime()) + "_" + firstNameTextField.getText() + "_" + LastNameTextField.getText() +  "_"  + voucherNumberTextFeild.getText();
            PdfItext pi = new PdfItext("/file/E_Voucher.pdf", fileName + ".pdf");
            String addonName;
            pi.fillFormField("Title", treatmentComboBox.getSelectedItem().toString());
            pi.fillFormField("Recipient", firstNameTextField.getText() + " " + LastNameTextField.getText());
            pi.fillFormField("VoucherNumber","Voucher Number: " +  voucherNumberTextFeild.getText());
            pi.fillFormField("Amount", "Number of treatment: " + amountTextFeild.getText());
            String treatmentDetail = mp.getC1().getContent(treatmentComboBox.getSelectedItem().toString());
            String addonDetail = mp.getC2().getContent(addonComboBox.getSelectedItem().toString());
            if (addonComboBox.getSelectedItem().toString().contains("None")) {
                pi.fillFormField("TreatmentDetail", treatmentComboBox.getSelectedItem().toString() + "\n" + treatmentDetail);
                pi.fillFormField("Treatment Name", treatmentComboBox.getSelectedItem().toString());
            } else {
                pi.fillFormField("Treatment Name", treatmentComboBox.getSelectedItem().toString() + " & " + addonComboBox.getSelectedItem().toString());
                addonName = "Add-On: " + addonComboBox.getSelectedItem().toString();
                pi.fillFormField("AddonName", addonName);
                pi.fillFormField("TreatmentDetail", treatmentDetail + "\n" + addonComboBox.getSelectedItem().toString() + "\n" + addonDetail);
            }
            c.add(Calendar.MONTH, +12);
            pi.fillFormField("Vaild up to and including", new SimpleDateFormat("dd/MM/yyyy").format(c.getTime()));
            pi.close();            
            PdfBox pb = new PdfBox(fileName);
            PdfItext pi1 = new PdfItext();
            pi1.imageToPDF(System.getProperty("user.dir") + "\\" + fileName + " forClient " + ".pdf",System.getProperty("user.dir") + "\\" + fileName + ".png");
            Desktop ds = Desktop.getDesktop();
            ds.open(new File(System.getProperty("user.dir") + "\\" + fileName + " forClient " + ".pdf"));
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printOutButtonActionPerformed

    private void voucherNumberTextFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voucherNumberTextFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_voucherNumberTextFeildActionPerformed

    private void amountTextFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTextFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTextFeildActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmountLabel;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JComboBox<String> addonComboBox;
    private javax.swing.JLabel addonLabel;
    private javax.swing.JTextField amountTextFeild;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton printOutButton;
    private javax.swing.JLabel serviceLabel;
    private javax.swing.JComboBox<String> treatmentComboBox;
    private javax.swing.JLabel voucherNumberLabel;
    private javax.swing.JTextField voucherNumberTextFeild;
    // End of variables declaration//GEN-END:variables
}
