package IkoiEVoucher;


import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Rick
 */
public final class MainFrame extends javax.swing.JFrame {

    private Content c1,c2;
    private ArrayList<String> serviceTitle,serviceDescription,addon,addonDescription;
    private DefaultComboBoxModel dcbm1,dcbm2;
    private LoadFile lf,lf2;
    private PdfItext pi;
    
    /**
     * Creates new form MainFrame
     *
     * @throws java.io.FileNotFoundException
     */
    public MainFrame() throws FileNotFoundException {
        this.lf = new LoadFile("F:/Try00/serviceManu.txt");
        this.serviceTitle = new ArrayList();
        this.serviceDescription = new ArrayList();
        this.addon = new ArrayList();
        this.addonDescription = new ArrayList();
        arrayInitialization();
        description();
        addOn();
        c1 = new Content(toArray(serviceTitle), toArray(serviceDescription));
        c2 = new Content(toArray(addon), toArray(addonDescription));
        this.dcbm1 = new DefaultComboBoxModel(serviceTitle.toArray());
        this.dcbm2 = new DefaultComboBoxModel(addon.toArray());
        initComponents();
    }

    public void arrayInitialization() throws FileNotFoundException {
        String content1 = "";
        String content2 = "";
        lf = new LoadFile();
        Scanner scanner = new Scanner(lf.getSrc());
        scanner.useDelimiter(";");
        while (scanner.hasNext()) {
            content1 += scanner.next();
            serviceTitle.add(content1);
            content1 = "";
            content2 += scanner.next();
        }
        scanner.close();
    }

    public void description() throws FileNotFoundException {
        String contentOne = "";
        String contentTwo = "";
        lf = new LoadFile();
        Scanner scanner = new Scanner(lf.getSrc());
        scanner.useDelimiter(";");
        while (scanner.hasNext()) {
            contentOne = scanner.next();
            contentOne = "";
            contentTwo = scanner.next();
            serviceDescription.add(contentTwo);
        }
        scanner.close();
    }
    
    public void addOn() throws FileNotFoundException{
        String contentThree = "";
        String contentFour = "";
        lf2 = new LoadFile("F:/Try00/addon.txt");
        Scanner scanner = new Scanner(lf2.getSrc());
        scanner.useDelimiter(";");
        while (scanner.hasNext()) {
            contentThree = scanner.next();
            addon.add(contentThree);
            contentFour = scanner.next();
            addonDescription.add(contentFour);
        }
        scanner.close();
    }
    
    public String[] toArray(ArrayList<String> al){
        String[] stra = new String[al.size()];
        for(int x = 0; x<al.size(); x++){
            stra[x]=al.get(x);
        }
        return stra;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrintOutButton = new javax.swing.JButton();
        treatmentComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RecipientTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ReseemableFrom = new javax.swing.JTextField();
        VailUpToAndIncluding = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addonComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PrintOutButton.setText("Print");
        PrintOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintOutButtonActionPerformed(evt);
            }
        });

        treatmentComboBox.setModel(dcbm1);
        treatmentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treatmentComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("treatment:");

        jLabel2.setText("Recipient:");

        RecipientTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecipientTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Reseemable From:");

        ReseemableFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReseemableFromActionPerformed(evt);
            }
        });

        VailUpToAndIncluding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VailUpToAndIncludingActionPerformed(evt);
            }
        });

        jLabel4.setText("Vaild up to and including:");

        jLabel5.setText("Add-on:");

        addonComboBox.setModel(dcbm2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PrintOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(VailUpToAndIncluding)
                            .addComponent(treatmentComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 397, Short.MAX_VALUE)
                            .addComponent(RecipientTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ReseemableFrom, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addonComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(treatmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(RecipientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReseemableFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VailUpToAndIncluding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addonComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PrintOutButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrintOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintOutButtonActionPerformed
        try {
            pi = new PdfItext(new File("F:/Try00/copy01.pdf"), new File("F:/Try00/copy.pdf"));
            pi.fillFormField("Title", treatmentComboBox.getSelectedItem().toString());
            pi.fillFormField("Recipient", RecipientTextField.getText());
            pi.fillFormField("Redeemable From", ReseemableFrom.getText());
            String treatmentDetail = c1.getContent(treatmentComboBox.getSelectedItem().toString()) + "\n" + c2.getContent(addonComboBox.getSelectedItem().toString());
            pi.fillFormField("Treatment Name", treatmentComboBox.getSelectedItem().toString());
            pi.fillFormField("TreatmentDetail", treatmentDetail);
            pi.fillFormField("Vaild up to and including", VailUpToAndIncluding.getText());
            pi.close();
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PrintOutButtonActionPerformed

    private void treatmentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treatmentComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_treatmentComboBoxActionPerformed

    private void RecipientTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecipientTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecipientTextFieldActionPerformed

    private void ReseemableFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReseemableFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReseemableFromActionPerformed

    private void VailUpToAndIncludingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VailUpToAndIncludingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VailUpToAndIncludingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainFrame().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PrintOutButton;
    private javax.swing.JTextField RecipientTextField;
    private javax.swing.JTextField ReseemableFrom;
    private javax.swing.JTextField VailUpToAndIncluding;
    private javax.swing.JComboBox<String> addonComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> treatmentComboBox;
    // End of variables declaration//GEN-END:variables
}
